#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           servoGate,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           flowMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           conveyorMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//line follower: 0-4095 light-dark


string marbleType;
/////////////////////////////////////////////
const int woodMin = 155;
const int woodMax = 165;

const int glassMin = 1700;
const int glassMax = 1900;

const int metalMin = 615; //	TODO
const int metalMax = 625; //	TODO

const int blueMin = 185; //	TODO
const int blueMax = 195; //	TODO
/////////////////////////////////////////////

void setConveyor(int marble);
const int WOOD_POSITION = -145;
const int GLASS_POSITION = 0;
const int METAL_POSITION = 51;
const int BLUE_POSITION = 146;

const int WOOD = 0;
const int GLASS = 1;
const int METAL = 2;
const int BLUE = 3;

/////////////////////////////////////////////



bool running = true;


task main()
{
	setServo(servoGate,-127);


	int marble = -1;
	marbleType = ""; //only for debugging purposes
	int currentValue = -1;
	turnFlashlightOn(flashlight, 127);//


	while(1==1){
		if(running){

		  startMotor(flowMotor, 12);
		  wait(.5);
		  stopMotor(flowMotor);

			//lineFollower code
		  wait(.5);
			currentValue = SensorValue(lineFollower);
			if(currentValue >= woodMin && currentValue <= woodMax) {marbleType = "wood"; marble = WOOD;} //if it's wood

			else if(currentValue >= glassMin && currentValue <= glassMax) {marbleType = "glass"; marble = GLASS;} //if it's glass

			else if(currentValue >= metalMin && currentValue <= metalMax) {marbleType = "metal"; marble = METAL;} //if it's metal

			else if(currentValue >= blueMin && currentValue <= blueMax) {marbleType = "blue plastic"; marble = BLUE;} //if it's blue plastic

			else marble = -1;

			//Moving base code
			setConveyor(GLASS);
			setServo(servoGate, 0);
			wait(1);
			setServo(servoGate, -127);
			wait(.5);

			if(SensorValue(bumpSwitch) == 1) running = false;
		}
		else if(SensorValue(bumpSwitch) == 1) {running = true; stopMotor(flowMotor);}

	}
}

void setConveyor(int marble){
	if(marble == -1){}

	else if(marble == WOOD && (SensorValue(encoder) != WOOD_POSITION) ) {
		startMotor(conveyorMotor,-20);

		untilBump(limitSwitch);
		stopMotor(conveyorMotor);
	}

	else if(marble == GLASS && SensorValue(encoder) != GLASS_POSITION) {
		if(SensorValue(encoder) < GLASS_POSITION){
			//setConveyor(WOOD);
			startMotor(conveyorMotor,20);
		}
		else{startMotor(conveyorMotor, -20);}

		while(SensorValue(encoder) != GLASS_POSITION){}
		stopMotor(conveyorMotor);
	}
	else if(marble == METAL) {
		if(SensorValue(encoder) != METAL_POSITION){
			setConveyor(BLUE);
			startMotor(conveyorMotor,-20);
			wait(2);
			stopMotor(conveyorMotor);
		}
	}

	else if(marble == BLUE && (SensorValue(encoder) != BLUE_POSITION)) {
		startMotor(conveyorMotor,20);
		untilBump(limitSwitch);
		stopMotor(conveyorMotor);
	}

}
